const Map<String, String> siStrings = <String, String>{

  // appt
  'appt.details': 'හමුවීමේ විස්තර',
  'appt.documentation': 'ලේඛන',
  'appt.errInvalidLink': 'වලංගු නොවන රැස්වීම් සබැඳියකි.',
  'appt.errNoZoomLink': 'Zoom රැස්වීම් සබැඳිය නොමැත.',
  'appt.errOpenZoom': 'Zoom රැස්වීම විවෘත කළ නොහැක.',
  'appt.join': 'හමුවීමට එක්වන්න',
  'appt.meetingId': 'රැස්වීම් අංකය',
  'appt.noDocs': 'වෛද්‍යවරයා තවම ලේඛන උඩුගත කර නැත.',
  'appt.passcode': 'මුරකේතය',
  'appt.platform': 'වේදිකාව',
  'appt.prescription': 'බෙහෙත් වට්ටෝරුව',
  'appt.uploadedBy': 'උඩුගත කළේ {name} • {date}',
  'appt.uploadedDocs': 'උඩුගත කළ ලේඛන',
  'appt.zoomDetails': 'Zoom රැස්වීම් විස්තර {doctor}',

  // article
  'article.all': 'සියල්ල',
  'article.allArticles': 'සියලු ලිපි',
  'article.articleCaps': 'ලිපිය',
  'article.articles': 'ලිපි',
  'article.by': 'කර්තෘ {author}',
  'article.errLoad': 'ලිපි පූරණය අසාර්ථකයි.',
  'article.introduction': 'හැඳින්වීම',
  'article.none': 'ලිපි හමු නොවීය.',
  'article.ourArticles': 'අපගේ ලිපි',
  'article.searchHint': 'අපගේ ලිපි 1242 සොයන්න',
  'article.suggestedTopics': 'යෝජිත මාතෘකා',
  'article.topicEdu': 'අධ්‍යාපනය',
  'article.topicHealth': 'සෞඛ්‍යය',
  'article.topicStatus': 'තත්ත්වය',
  'article.topicStress': 'ආතතිය',
  'article.unknownAuthor': 'නොදනී',

  // auth
  'auth.errPhoneFormat': 'දුරකථන අංකය වලංගු ශ්‍රී ලාංකික ජංගම අංකයක් විය යුතුය (උදා. 0775455266).',
  'auth.yourPhone': 'ඔබගේ දුරකථනය',

  // chat
  'chat.aiHelpers': 'AI සහායකයන්',
  'chat.askAnything': 'ඕනෑම දෙයක් අසන්න...',
  'chat.chat': 'කතාබහ',
  'chat.errHistory': 'සංවාද ඉතිහාසය පූරණය කළ නොහැකි විය.',
  'chat.errOlder': 'පැරණි පණිවිඩ පූරණය කළ නොහැකි විය.',
  'chat.errResponse': 'සමාවන්න, පිළිතුරක් ලබා ගත නොහැකි විය. කරුණාකර නැවත උත්සාහ කරන්න.',
  'chat.history': 'ඉතිහාසය',

  // chatHist
  'chatHist.deleteAll': 'සියලු සංවාද මකන්නද?',
  'chatHist.errDeleteAll': 'සංවාද මකා දැමිය නොහැකි විය.',
  'chatHist.errDeleteOne': 'සංවාදය මකා දැමිය නොහැකි විය.',
  'chatHist.errLoad': 'ඉතිහාසය පූරණය කළ නොහැකි විය. සේවාදායකය ක්‍රියාත්මකද?',
  'chatHist.noMatch': 'සමාවන්න, ඔබගේ සෙවීමට ගැළපෙන\nපණිවිඩයක් නැත',
  'chatHist.notFound': 'හමු නොවීය',
  'chatHist.searchHint': 'සොයන්න...',

  // checkout
  'checkout.bookingFee': 'වෙන්කිරීමේ ගාස්තුව',
  'checkout.continueToPayment': 'ගෙවීමට ඉදිරියට',
  'checkout.date': 'දිනය',
  'checkout.doctor': 'වෛද්‍යවරයා',
  'checkout.doctorFee': 'වෛද්‍ය ගාස්තුව',
  'checkout.paymentDetails': 'ගෙවීම් විස්තර',
  'checkout.speciality': 'විශේෂඥතාව',
  'checkout.subtitle': 'ගෙවීමට යාමට පෙර කරුණාකර විස්තර පරීක්ෂා කරන්න',
  'checkout.time': 'වේලාව',
  'checkout.title': 'ගෙවීම',
  'checkout.totalFee': 'මුළු ගාස්තුව',

  // common
  'common.back': 'ආපසු',
  'common.cancel': 'අවලංගු කරන්න',
  'common.close': 'වසන්න',
  'common.confirm': 'තහවුරු කරන්න',
  'common.continue': 'ඉදිරියට',
  'common.delete': 'මකන්න',
  'common.done': 'නිම කළා',
  'common.edit': 'සංස්කරණය',
  'common.error': 'යම් දෝෂයක් සිදු විය',
  'common.loading': 'පූරණය වෙමින්...',
  'common.next': 'ඊළඟ',
  'common.no': 'නැහැ',
  'common.ok': 'හරි',
  'common.retry': 'නැවත උත්සාහ කරන්න',
  'common.save': 'සුරකින්න',
  'common.saving': 'සුරකිමින්...',
  'common.search': 'සොයන්න',
  'common.seeAll': 'සියල්ල බලන්න',
  'common.skip': 'මඟ හරින්න',
  'common.submit': 'යොමු කරන්න',
  'common.today': 'අද',
  'common.tomorrow': 'හෙට',
  'common.tryAgain': 'කරුණාකර නැවත උත්සාහ කරන්න',
  'common.yes': 'ඔව්',
  'common.yesterday': 'ඊයේ',

  // community
  'community.addComment': 'අදහසක් එක් කරන්න...',
  'community.addPhoto': 'ඡායාරූපයක් එක් කරන්න',
  'community.all': 'සියල්ල',
  'community.captionHint': 'සිරස්තලයක් ලියන්න...',
  'community.createFailed': 'පළකිරීම සෑදීම අසාර්ථකයි',
  'community.noPosts': 'පළකිරීම් හමු නොවීය',
  'community.photos': 'ඡායාරූප',
  'community.post': 'පළ කරන්න',
  'community.title': 'ප්‍රජාව',
  'community.user': 'පරිශීලක',
  'community.whatsHappening': 'මොකද වෙන්නේ?',
  'community.yourPosts': 'ඔබගේ පළකිරීම්',

  // comp
  'comp.awaiting': 'බලාපොරොත්තුවෙන්',
  'comp.buildCircle': 'ඔබගේ කවය ගොඩනඟන්න',
  'comp.connected': 'සම්බන්ධයි',
  'comp.emailHint': 'name@example.com',
  'comp.intro': 'ගමන එකට අත්විඳින්න. ඔබගේ සහකරු සමඟ\nයුගල වී අදහස් බෙදාගෙන පහසුවෙන්\nසම්බන්ධව සිටින්න.',
  'comp.intro1': 'ගමන එකට අත්විඳින්න. ඔබගේ\n',
  'comp.intro2': 'සහකරු සමඟ යුගල වී අදහස් බෙදාගෙන\n',
  'comp.intro3': 'පහසුවෙන් සම්බන්ධව සිටින්න.',
  'comp.inviteResent': 'ආරාධනය සාර්ථකව නැවත යවන ලදී.',
  'comp.partnerEmail': 'සහකරුගේ ඊමේල්',
  'comp.privacySettings': 'පෞද්ගලිකත්ව සැකසුම්',
  'comp.remove': 'ඉවත් කරන්න',
  'comp.removeBody': 'මෙය ඔබගේ සහායක වෙන් කරයි. ඔවුන්ට තවදුරටත් ඔබගේ දත්ත වෙත ප්‍රවේශය නොලැබේ.',
  'comp.removeCompanion': 'සහායක ඉවත් කරන්න',
  'comp.removeTitle': 'සහායක ඉවත් කරන්නද?',
  'comp.removed': 'සහායක ඉවත් කරන ලදී.',
  'comp.resendInvite': 'ආරාධනය නැවත යවන්න',
  'comp.sendDifferent': 'වෙනත් ඊමේල් එකකට යවන්න',
  'comp.sendInvite': 'ආරාධනය යවන්න',
  'comp.title': 'සහායක',
  'comp.waitingPartner': 'ඔබගේ සහකරු එක්වන තුරු බලා සිටී…',

  // compDash
  'compDash.card.doctor': 'වෛද්‍ය\nහමුවීම්',
  'compDash.card.mood': 'මනෝභාව\nදිනපොත',
  'compDash.card.todo': 'කළ යුතු\nලැයිස්තුව',
  'compDash.card.tracking': 'නිරීක්ෂණ\nපද්ධතිය',
  'compDash.everythingGeneric': 'ඔවුන්ට අවශ්‍ය සියල්ල',
  'compDash.everythingNamed': '{name}ට අවශ්‍ය සියල්ල',
  'compDash.noSharedInfo': 'රෝගියා තවම කිසිදු තොරතුරක් බෙදාගෙන නැත.',
  'compDash.plansGeneric': 'අද සැලසුම්',
  'compDash.plansNamed': 'අද {name}ගේ සැලසුම්',
  'compDash.supporting': '{name}ට සහාය වෙමින්',

  // compSent
  'compSent.body1': 'අපි මැජික් සබැඳියක් යැව්වා\n',
  'compSent.body2': ' වෙත. ඔවුන් පිළිගත් පසු,\nඔබ Sanctuary තුළ සම්බන්ධ\nවනු ඇත.',
  'compSent.continue': 'ඉදිරියට →',
  'compSent.pending': 'සහකරු බලාපොරොත්තුවෙන්',
  'compSent.sent': 'යවන ලදී',
  'compSent.title': 'ආරාධනය යවන ලදී!',

  // compTodo
  'compTodo.errLoad': 'කාර්ය පූරණය කළ නොහැකි විය.',
  'compTodo.none': 'අද සඳහා කාර්ය නැත.',
  'compTodo.readOnly': 'කියවීම පමණි · අද',
  'compTodo.restricted': 'රෝගියා ඔවුන්ගේ කළ යුතු ලැයිස්තුවට ප්‍රවේශය සීමා කර ඇත.',

  // compTrack
  'compTrack.errLoad': 'ඖෂධ කාලසටහන පූරණය කළ නොහැකි විය.',
  'compTrack.none': 'අද සඳහා ඖෂධ නියම කර නොමැත.',
  'compTrack.progress': 'අද දින ප්‍රගතිය',
  'compTrack.restricted': 'රෝගියා ඔවුන්ගේ නිරීක්ෂකයට ප්‍රවේශය සීමා කර ඇත.',
  'compTrack.takenRatio': '{taken}/{total} ගෙන ඇත',
  'compTrack.title': 'ඖෂධ නිරීක්ෂකය',

  // dash
  'dash.card.chatbot': 'චැට්බොට්',
  'dash.card.community': 'ප්‍රජා\nකණ්ඩායම් කතාව',
  'dash.card.companion': 'සහායකයෙකු\nසම්බන්ධ කරන්න',
  'dash.card.doctor': 'වෛද්‍යවරයෙකු\nසම්බන්ධ කරන්න',
  'dash.card.donation': 'පරිත්‍යාග\nඉල්ලීම',
  'dash.card.moodJournal': 'මනෝභාව\nදිනපොත',
  'dash.card.todo': 'කළ යුතු ලැයිස්තුව',
  'dash.card.tracking': 'නිරීක්ෂණ\nපද්ධතිය',
  'dash.card.video': 'වීඩියෝ\nනිර්දේශ',
  'dash.everythingYouNeed': 'ඔබට අවශ්‍ය සියල්ල',
  'dash.greetingAnon': 'ආයුබෝවන්!',
  'dash.greetingNamed': 'ආයුබෝවන්, {name}!',
  'dash.mindfulResources': 'සිහිකල්පනා සම්පත්',
  'dash.noPlans': 'අද සඳහා සැලසුම් නැත.',
  'dash.plansForToday': 'අද ඔබගේ සැලසුම්',
  'dash.quoteOfDay': 'දවසේ වදන',

  // doc
  'doc.appointment': 'වෛද්‍ය හමුවීම',
  'doc.biography': 'චරිතාපදානය',
  'doc.bookAppointment': 'හමුවීම වෙන් කරන්න',
  'doc.calendar': 'දින දර්ශනය',
  'doc.catCounsellor': 'උපදේශක',
  'doc.catOncologist': 'පිළිකා විශේෂඥ',
  'doc.catPsychologist': 'මනෝ විද්‍යාඥ',
  'doc.categories': 'ප්‍රවර්ග',
  'doc.detail': 'වෛද්‍ය විස්තර',
  'doc.errSelectDateTime': 'කරුණාකර දිනයක් සහ වේලාවක් තෝරන්න.',
  'doc.getMoreInfo': 'වැඩිදුර තොරතුරු ලබා ගන්න',
  'doc.mySessions': 'මගේ සැසි',
  'doc.noDoctors': 'වෛද්‍යවරු හමු නොවීය',
  'doc.searchHint': 'වෛද්‍යවරයෙකු සොයන්න...',
  'doc.specialty': 'විශේෂඥතාව: {specialty}',
  'doc.specialtyNA': 'විශේෂඥතාව නොමැත',
  'doc.time': 'වේලාව',

  // donation
  'donation.approvedBody': 'ඔබගේ සහතික සහ ලේඛන අපගේ අනුකූලතා\nකණ්ඩායම විසින් සත්‍යාපනය කර ඇත.',
  'donation.chooseFile': 'ගොනුව තෝරන්න',
  'donation.docApproved': 'ලේඛනය අනුමතයි',
  'donation.docRejected': 'ලේඛනය ප්‍රතික්ෂේපයි',
  'donation.docStatus': 'ලේඛන තත්ත්වය',
  'donation.docTitle': 'ලේඛන මාතෘකාව',
  'donation.errActiveApp': 'ඔබට දැනටමත් ක්‍රියාකාරී පරිත්‍යාග අයදුම්පතක් ඇත.',
  'donation.errChooseFile': 'කරුණාකර පළමුව ගොනුවක් තෝරන්න.',
  'donation.errSubmit': 'යොමු කිරීම අසාර්ථකයි. කරුණාකර නැවත උත්සාහ කරන්න.',
  'donation.inReview': 'සමාලෝචනයේ',
  'donation.makeARequest': 'ඉල්ලීමක් කරන්න',
  'donation.makeRequest': 'ඉල්ලීමක් කරන්න',
  'donation.medicalDoc': 'වෛද්‍ය ලේඛනය',
  'donation.noFile': 'ගොනුවක් තෝරා නැත',
  'donation.rejectedBody': 'ලබා දුන් ලේඛන මගින් ඔබගේ අනන්‍යතාවය සත්‍යාපනය කළ නොහැකි විය.',
  'donation.requestTitle': 'පරිත්‍යාග ඉල්ලීම',
  'donation.resubmit': 'නැවත යොමු කරන්න',
  'donation.reviewBody': 'ඔබගේ ලේඛනය දැනට අපගේ පරිපාලකයින් විසින් සමාලෝචනය කරමින් පවතී.\nප්‍රතිඵල ඉක්මනින් ලබා දෙනු ඇත.',
  'donation.statusApproved': 'අනුමතයි',
  'donation.statusRejected': 'ප්‍රතික්ෂේපයි',
  'donation.statusWaiting': 'බලාපොරොත්තුවෙන්',
  'donation.submitDoc': 'ලේඛනය යොමු කරන්න',
  'donation.tapToUpload': 'උඩුගත කිරීමට තට්ටු කරන්න',
  'donation.uploadDoc': 'ලේඛනය උඩුගත කරන්න',

  // editProfile
  'editProfile.backToDash': 'උපකරණ පුවරුවට ආපසු',
  'editProfile.passwordHint': 'වත්මන් එක තබා ගැනීමට හිස්ව තබන්න',
  'editProfile.phoneHint': '07XXXXXXXX',
  'editProfile.saveChanges': 'වෙනස්කම් සුරකින්න',
  'editProfile.saved': 'ඔබගේ වෙනස්කම් සාර්ථකව සුරකින ලදී',
  'editProfile.title': 'පැතිකඩ සංස්කරණය',

  // emailVerify
  'emailVerify.afterHint': 'සත්‍යාපනය කිරීමෙන් පසු, OTP සැකසීමට \'ඉදිරියට\' ඔබන්න.',
  'emailVerify.continue': 'ඉදිරියට',
  'emailVerify.notYet': 'ඊමේල් තවම සත්‍යාපනය කර නැත. කරුණාකර ඔබගේ inbox පරීක්ෂා කරන්න.',
  'emailVerify.resend': 'ඊමේල් නැවත යවන්න',
  'emailVerify.resent': 'සත්‍යාපන ඊමේල් නැවත යවන ලදී.',
  'emailVerify.sentTo': 'අපි සත්‍යාපන සබැඳියක් යැව්වේ:',
  'emailVerify.title': 'ඔබගේ ඊමේල් සත්‍යාපනය කරන්න',

  // forgot
  'forgot.body': 'මුරපදය යළි පිහිටුවීමේ උපදෙස් ලබා ගැනීමට\nපහත ඔබගේ ලියාපදිංචි ඊමේල් ඇතුළත් කරන්න',
  'forgot.body1': 'පහත ඔබගේ ලියාපදිංචි ඊමේල් ඇතුළත් කරන්න\n',
  'forgot.body2': 'මුරපදය යළි පිහිටුවීමේ උපදෙස් ලබා ගැනීමට',
  'forgot.emailHint': 'ඔබගේ ඊමේල් ඇතුළත් කරන්න...',
  'forgot.errSend': 'යළි පිහිටුවීමේ සබැඳිය යැවිය නොහැක. කරුණාකර නැවත උත්සාහ කරන්න.',
  'forgot.heading': 'ඔබගේ මුරපදය අමතක වුණාද?',
  'forgot.login': 'පිවිසෙන්න',
  'forgot.remember': 'මුරපදය මතකද? ',
  'forgot.send': 'යවන්න',
  'forgot.title': 'මුරපදය අමතකද',

  // forgotSuccess
  'forgotSuccess.body': 'වැඩිදුර උපදෙස් සඳහා කරුණාකර ඔබගේ inbox පරීක්ෂා කරන්න.',
  'forgotSuccess.noLink': 'සබැඳිය ලැබුණේ නැද්ද? ',
  'forgotSuccess.resend': 'නැවත යවන්න',
  'forgotSuccess.sent': 'ඊමේල් යවා ඇත!',
  'forgotSuccess.signIn': 'පිවිසෙන්න',

  // journal
  'journal.addPhoto': 'ඡායාරූපයක් එක් කරන්න',
  'journal.create': 'දිනපොත සාදන්න',
  'journal.entryHint': 'අද මට නරක දවසක්, පාසලේදී...\nකමක් නෑ කියලා හිතනවා...',
  'journal.errFields': 'කරුණාකර මාතෘකාව සහ සටහන දෙකම පුරවන්න',
  'journal.newEntry': 'නව දිනපොත් සටහන',
  'journal.selectEmotion': 'ඔබගේ හැඟීම තෝරන්න',
  'journal.titleHint': 'නැවතත් නරක හැඟීමක්',
  'journal.titleLabel': 'දිනපොත් මාතෘකාව',
  'journal.writeEntry': 'ඔබගේ සටහන ලියන්න',

  // legal
  'legal.englishNotice': 'මෙම ලේඛනය ඉංග්‍රීසි භාෂාවෙන් පමණක් ලබා ගත හැකිය. නීතිමය වශයෙන් බැඳී ඇත්තේ ඉංග්‍රීසි අනුවාදයයි.',
  'legal.privacyTitle': 'පෞද්ගලිකත්ව ප්‍රතිපත්තිය',
  'legal.termsTitle': 'සේවා කොන්දේසි',

  // login
  'login.emailLabel': 'ඊමේල් ලිපිනය',
  'login.errBothFields': 'කරුණාකර ඊමේල් සහ මුරපදය දෙකම ඇතුළත් කරන්න.',
  'login.errInvalidEmail': 'කරුණාකර වලංගු ඊමේල් ලිපිනයක් ඇතුළත් කරන්න.',
  'login.errOtpStart': 'OTP සත්‍යාපනය ආරම්භ කළ නොහැක.',
  'login.errWrongPassword': 'මුරපදය වැරදියි. කරුණාකර නැවත උත්සාහ කරන්න.',
  'login.forgotPassword': 'මුරපදය අමතකද',
  'login.noAccount': 'ගිණුමක් නැද්ද? ',
  'login.passwordHint': 'ඔබගේ මුරපදය ඇතුළත් කරන්න...',
  'login.passwordLabel': 'මුරපදය',
  'login.signIn': 'පිවිසෙන්න',
  'login.signUp': 'ලියාපදිංචි වන්න',

  // month
  'month.full.1': 'ජනවාරි',
  'month.full.10': 'ඔක්තෝබර්',
  'month.full.11': 'නොවැම්බර්',
  'month.full.12': 'දෙසැම්බර්',
  'month.full.2': 'පෙබරවාරි',
  'month.full.3': 'මාර්තු',
  'month.full.4': 'අප්‍රේල්',
  'month.full.5': 'මැයි',
  'month.full.6': 'ජූනි',
  'month.full.7': 'ජූලි',
  'month.full.8': 'අගෝස්තු',
  'month.full.9': 'සැප්තැම්බර්',
  'month.short.1': 'ජන',
  'month.short.10': 'ඔක්',
  'month.short.11': 'නොවැ',
  'month.short.12': 'දෙසැ',
  'month.short.2': 'පෙබ',
  'month.short.3': 'මාර්',
  'month.short.4': 'අප්',
  'month.short.5': 'මැයි',
  'month.short.6': 'ජූනි',
  'month.short.7': 'ජූලි',
  'month.short.8': 'අගෝ',
  'month.short.9': 'සැප්',

  // mood
  'mood.good': 'හොඳයි',
  'mood.goodDesc': 'මට සතුටක් දැනේ.',
  'mood.great': 'ඉතා හොඳයි',
  'mood.greatDesc': 'මට අපූරු හැඟීමක් දැනේ.',
  'mood.low': 'පහළ',
  'mood.lowDesc': 'මට දුකක් දැනේ.',
  'mood.normal': 'සාමාන්‍ය',
  'mood.normalDesc': 'මට මධ්‍යස්ථ හැඟීමක් දැනේ.',
  'mood.veryLow': 'ඉතා පහළ',
  'mood.veryLowDesc': 'මට ඉතා පහත් හැඟීමක් දැනේ.',

  // moodSel
  'moodSel.checkIn': 'අපි බලමු',
  'moodSel.heading': 'ඔබගේ මනෝභාවය\nකෙසේ විස්තර කරන්නද?',
  'moodSel.title': 'මනෝභාව දිනපොත',

  // moodStatus
  'moodStatus.keepJournaling': 'මනෝභාව රටාවක් සෑදීමට දිනපොත ලිවීම දිගටම කරන්න.',
  'moodStatus.moodLabel': 'මනෝභාවය: {mood}',
  'moodStatus.needSupport': 'අද මෙම පුද්ගලයාට ඔබගේ සහාය අවශ්‍ය විය හැක.',
  'moodStatus.noHistory': 'තවම ඉතිහාසයක් නැත. ඔබගේ පළමු දිනපොත් සටහන එක් කරන්න.',
  'moodStatus.recentJournals': 'මෑත දිනපොත්',
  'moodStatus.viewAll': 'සියල්ල බලන්න',

  // notif
  'notif.earlierToday': 'අද කලින්',
  'notif.lastWeek': 'පසුගිය සතියේ',
  'notif.markAllRead': 'සියල්ල කියවූ බව සලකුණු කරන්න',
  'notif.medTitle': '{name} ගැනීමට වේලාවයි',
  'notif.moodBody': 'ඔබගේ මනෝභාවය සටහන් කරන්න',
  'notif.moodTitle': 'අද ඔබට කෙසේ දැනෙනවාද?',
  'notif.none': 'තවම දැනුම්දීම් නැත',
  'notif.taskBody': 'නියමිත වේලාව {time}',
  'notif.taskTitle': '{title} ඉක්මනින් නියමිතයි',
  'notif.thisMonth': 'මෙම මාසයේ',
  'notif.title': 'දැනුම්දීම්',

  // otp
  'otp.body': 'ඔබගේ අංකයට OTP එකක් යවා ඇත',
  'otp.continue': 'ඉදිරියට  →',
  'otp.heading': 'ඉලක්කම් 6ක OTP කේතය ඇතුළත් කරන්න',
  'otp.noCode': 'OTP එක ලැබුණේ නැද්ද? ',
  'otp.resend': 'නැවත යවන්න.',
  'otp.title': 'OTP සැකසුම',

  // past
  'past.activeDays': 'මෙම වසරේ ක්‍රියාකාරී දිනපොත් දින.',
  'past.allJournals': 'සියලු දිනපොත්',
  'past.details': 'දිනපොත් විස්තර',
  'past.entry': 'සටහන',
  'past.loadMoreFailed': 'තවත් සටහන් පූරණය කළ නොහැකි විය.',
  'past.mood': 'මනෝභාවය',
  'past.moodCaps': 'මනෝභාවය: {mood}',
  'past.newest': 'අලුත්ම',
  'past.noEntries': 'තවම දිනපොත් සටහන් නැත.',
  'past.oldest': 'පැරණිම',
  'past.patientEntries': 'රෝගියාගේ සටහන්',
  'past.swipeForMore': 'තවත් සඳහා ස්වයිප් කරන්න',
  'past.tapToRead': 'සම්පූර්ණ දිනපොත කියවීමට තට්ටු කරන්න',
  'past.tapToReadDated': '{day}/{month} • සම්පූර්ණ දිනපොත කියවීමට තට්ටු කරන්න',
  'past.title': 'මාතෘකාව',
  'past.yourEntries': 'ඔබගේ සටහන්',

  // payment
  'payment.cardNumber': 'කාඩ්පත් අංකය',
  'payment.cardholder': 'කාඩ්පත් හිමියාගේ නම',
  'payment.cvv': 'CVV',
  'payment.expDate': 'කල් ඉකුත්වන දිනය',
  'payment.pay': 'ගෙවන්න',
  'payment.selectMethod': 'ගෙවීම් ක්‍රමය තෝරන්න',

  // privacy
  'privacy.doctorAppts': 'වෛද්‍ය හමුවීම්',
  'privacy.doctorDesc': 'ඉදිරි වෛද්‍ය හමුවීම් ඔබගේ\nසහායකට දැකීමට ඉඩ දෙන්න',
  'privacy.moodDesc': 'ඔබගේ මනෝභාව සටහන් සහායකට\nදැකීමට ඉඩ දෙන්න',
  'privacy.moodJournal': 'මනෝභාව දිනපොත',
  'privacy.saved': 'පෞද්ගලිකත්ව සැකසුම් සුරකින ලදී.',
  'privacy.subtitle': 'ඔබගේ ගමනෙන් කොපමණක් සහායක සමඟ\nබෙදාගන්නේද යන්න පාලනය කරන්න.',
  'privacy.title': 'ඔබගේ අවකාශය, ඔබගේ\nකොන්දේසි',
  'privacy.todo': 'කළ යුතු ලැයිස්තුව',
  'privacy.todoDesc': 'ඔබගේ දෛනික කාර්ය සහ\nප්‍රමුඛතා බෙදාගන්න',
  'privacy.tracking': 'නිරීක්ෂණය',
  'privacy.trackingDesc': 'සෞඛ්‍ය සහ ක්‍රියාකාරකම්\nදත්ත බෙදාගැනීම සක්‍රීය කරන්න',

  // privacyDoc
  'privacyDoc.s1': '1. අප රැස් කරන දේ',
  'privacyDoc.s10': '10. මෙම ප්‍රතිපත්තියේ වෙනස්කම්',
  'privacyDoc.s11': '11. අප හා සම්බන්ධ වන්න',
  'privacyDoc.s2': '2. ඔබගේ තොරතුරු අප භාවිත කරන ආකාරය',
  'privacyDoc.s3': '3. Ayu වැඩිදියුණු කිරීමට ඔබගේ දත්ත භාවිත කරන ආකාරය',
  'privacyDoc.s4': '4. ඔබගේ තොරතුරු දැකිය හැක්කේ කාටද',
  'privacyDoc.s5': '5. අර්බුද හඳුනාගැනීම',
  'privacyDoc.s6': '6. ඔබගේ දත්ත ආරක්ෂිතව තබා ගැනේ',
  'privacyDoc.s7': '7. ඔබගේ දත්ත තබා ගන්නා කාලය',
  'privacyDoc.s8': '8. ඔබගේ අයිතිවාසිකම්',
  'privacyDoc.s9': '9. දරුවන්',

  // quiz
  'quiz.back': 'ආපසු',
  'quiz.cancerType': 'පිළිකා වර්ගය',
  'quiz.cancerTypeHint': 'උදා., ලියුකේමියා, ලිම්ෆෝමා, ආදිය',
  'quiz.dobCelebrate': 'අපි ඔබ සමඟ සමරන්නෙමු!',
  'quiz.dobSubtitle': 'ඔබගේ උපන්දිනය සමරන්නට\nඅපි කැමතියි!',
  'quiz.dobTitle': 'ඔබ උපන්නේ කවදාද?',
  'quiz.dobYearHint': 'වර්ෂය',
  'quiz.errPickStory': 'කරුණාකර ඔබ කැමති කථා වර්ගයක් වත් තෝරන්න.',
  'quiz.errSave': 'පැතිකඩ සුරැකිය නොහැකි විය: {error}',
  'quiz.finish': 'අවසන් කරන්න',
  'quiz.genderFemale': 'ගැහැණු',
  'quiz.genderMale': 'පිරිමි',
  'quiz.genderSubtitle': 'ඔබ ගැන ටිකක් කියන්න',
  'quiz.genderTitle': 'ඔබ ඔබවම විස්තර කරන්නේ කෙසේද?',
  'quiz.genderTrans': 'සංක්‍රාන්ති ලිංගික',
  'quiz.healthSubtitle': 'ඔබගේ සෞඛ්‍යය ගැන කියන්න (සියල්ල විකල්පයි)',
  'quiz.healthTitle': 'ඔබගේ සෞඛ්‍ය ගමන',
  'quiz.interestCalm': 'සන්සුන් හා සාමකාමී',
  'quiz.interestDoc': 'වාර්තා චිත්‍රපට',
  'quiz.interestEdu': 'අධ්‍යාපනික',
  'quiz.interestMusic': 'ගී හා සංගීතය',
  'quiz.interestScience': 'විද්‍යාව',
  'quiz.interestSubtitle': 'ඔබට රසවත් යැයි හැඟෙන දේ තෝරන්න!\n(එකකට වඩා තෝරාගත හැක)',
  'quiz.interestTitle': 'ඔබ කැමති කුමන ආකාරයේ කථාවලටද?',
  'quiz.introLine1': 'ඔබ ගැන දැන ගැනීමට කැමතියි... කරුණාකර\n',
  'quiz.introLine2': ' කරුණු කිහිපයක්?',
  'quiz.moodCalm': 'සන්සුන් හා හොඳින්',
  'quiz.moodHappy': 'සතුටින් හා උද්යෝගයෙන්',
  'quiz.moodSad': 'ටිකක් දුකින්',
  'quiz.moodSubtitle': 'වැරදි පිළිතුරක් නැත.\nඅවංකව කියන්න',
  'quiz.moodTitle': 'ඔබට දැන් දැනෙන්නේ කෙසේද?',
  'quiz.moodWorried': 'කනස්සල්ලෙන් හෝ බියෙන්',
  'quiz.next': 'ඊළඟ',
  'quiz.preferNotSay': 'කීමට අකමැති',
  'quiz.progress': '{total}න් {current}',
  'quiz.relBuddhist': 'බෞද්ධ',
  'quiz.relChristian': 'ක්‍රිස්තියානි',
  'quiz.relHindu': 'හින්දු',
  'quiz.relMuslim': 'මුස්ලිම්',
  'quiz.relOther': 'වෙනත්',
  'quiz.religionSubtitle': 'සම්පූර්ණයෙන්ම විකල්පයි.\nමෙය ඔබගේ ගමන පෞද්ගලීකරණයට උපකාරී වේ',
  'quiz.religionTitle': 'ඔබට ආගමක් හෝ විශ්වාසයක් තිබේද?',
  'quiz.stageAdvanced': 'දියුණු',
  'quiz.stageEarly': 'මුල්',
  'quiz.stageNotSure': 'විශ්වාස නැත',
  'quiz.stageRemission': 'සුවවෙමින්',
  'quiz.stageTitle': 'ඔබ සිටින්නේ කුමන අවධියේද?',
  'quiz.step1': 'පියවර 1',
  'quiz.title': 'ප්‍රශ්නාවලිය',
  'quiz.treatChemo': 'රසායනික ප්‍රතිකාර',
  'quiz.treatNone': 'දැනට කිසිවක් නැත',
  'quiz.treatRadiation': 'විකිරණ ප්‍රතිකාර',
  'quiz.treatSurgery': 'සැත්කම',
  'quiz.treatmentTitle': 'වත්මන් ප්‍රතිකාරය',

  // quote
  'quote.buddhist.0': 'සිත සියල්ලයි. ඔබ සිතන දේ ඔබ බවට පත් වේ.',
  'quote.buddhist.1': 'ගෙවී ගිය දේ අත් හරින්න.',
  'quote.buddhist.2': 'සෑම උදෑසනකම අපි නැවත උපදිමු.',
  'quote.buddhist.3': 'සාමය ආරම්භ වන්නේ එක් හුස්මකින්.',
  'quote.buddhist.4': 'කරුණාව සියලු සුවයේ මූලයයි.',
  'quote.buddhist.5': 'ඔබම වෙහෙසිය යුතුය.',
  'quote.buddhist.6': 'කළ කුඩා දේ සැලසුම් කළ මහත් දේට වඩා හොඳය.',
  'quote.christian.0': 'දෙවියන් සමඟ, සියල්ල කළ හැකිය.',
  'quote.christian.1': 'නිසලව සිට මම දෙවියන් බව දැනගන්න.',
  'quote.christian.2': 'බිය නොවන්න, මම ඔබ සමඟය.',
  'quote.christian.3': 'ප්‍රීතිය උදෑසන පැමිණේ.',
  'quote.christian.4': 'ක්‍රිස්තුස් වහන්සේ තුළින් මට සියල්ල කළ හැකිය.',
  'quote.christian.5': 'ඔබගේ කරදර උන් වහන්සේට භාර දෙන්න; උන් වහන්සේ සැලකිලිමත් වේ.',
  'quote.christian.6': 'ස්වාමීන් වහන්සේ මාගේ එඬේරාය.',
  'quote.companion.0': 'මෙහිදී ඔබ තනිවම නොවේ.',
  'quote.companion.1': 'කුඩා සැලකිලිමත් ක්‍රියා විශාල වෙනසක් කරයි.',
  'quote.companion.2': 'ඔබගේ සහාය වචනවලට වඩා අර්ථවත්ය.',
  'quote.companion.3': 'එතැන සිටීම විශාලතම තෑග්ගයි.',
  'quote.companion.4': 'කරුණාව සියලු සුවයේ මූලයයි.',
  'quote.companion.5': 'එකට සිටින විට, සෑම පියවරක්ම සැහැල්ලුයි.',
  'quote.companion.6': 'ඔබගේ කරුණාව ශක්තියේ මූලාශ්‍රයකි.',
  'quote.hindu.0': 'ඔබගේ යුතුකම කර ඉතිරිය දෙවියන්ට භාර දෙන්න.',
  'quote.hindu.1': 'ප්‍රතිඵලයට ඇලුම් නොවී ක්‍රියා කරන්න.',
  'quote.hindu.2': 'ධර්මය ඇති තැන ජයග්‍රහණය ඇත.',
  'quote.hindu.3': 'ආත්මය කිසිදා සැබවින්ම නැති නොවේ.',
  'quote.hindu.4': 'ධෛර්යය ඔබගේ ශ්‍රේෂ්ඨතම ගුණයයි.',
  'quote.hindu.5': 'ඔබගේ ක්‍රියා ඔබගේ වටිනාකම් පිළිබිඹු කරත්වා.',
  'quote.hindu.6': 'ඔබගේ ගැඹුරු ආශාව කුමක්ද, ඔබ එයයි.',
  'quote.muslim.0': 'දුෂ්කරතාව සමඟ පහසුව පැමිණේ.',
  'quote.muslim.1': 'අල්ලාහ් හැකියාවට වඩා බර නොපටවයි.',
  'quote.muslim.2': 'උන් වහන්සේ සිහි කිරීමෙන් හදවත් සැනසුම ලබයි.',
  'quote.muslim.3': 'ඉවසන්න. අල්ලාහ් ඉවසිලිවන්තයන් සමඟය.',
  'quote.muslim.4': 'හොඳ දෙයක් කියන්න, නැතිනම් නිහඬව සිටින්න.',
  'quote.muslim.5': 'අල්ලාහ් විශ්වාස කර ක්‍රියා කරන්න.',
  'quote.muslim.6': 'සෑම දුෂ්කරතාවකම සැඟවුණු කරුණාවක් ඇත.',
  'quote.other.0': 'ඔබ සිතනවාට වඩා ඔබ ශක්තිමත්ය.',
  'quote.other.1': 'සුවවීමට කාලය ගතවේ, එය කමක් නැත.',
  'quote.other.2': 'දිනකට එකක් බැගින්.',
  'quote.other.3': 'කුඩා පියවර පවා ඔබව ඉදිරියට ගෙන යයි.',
  'quote.other.4': 'මෙහිදී ඔබ තනිවම නොවේ.',
  'quote.other.5': 'හුස්මක් ගන්න. ඔබට පුළුවන්.',
  'quote.other.6': 'මෙයද ගෙවී යනු ඇත.',

  // sessions
  'sessions.done': 'නිම',
  'sessions.late': 'ප්‍රමාද',
  'sessions.myAppts': 'මගේ හමුවීම්',
  'sessions.none': 'තවම හමුවීම් නැත',
  'sessions.past': 'පසුගිය',
  'sessions.patientAppts': 'රෝගියාගේ හමුවීම්',
  'sessions.upcoming': 'ඉදිරියේ',

  // settings
  'settings.language': 'භාෂාව',
  'settings.languageChanged': 'භාෂාව යාවත්කාලීන කරන ලදී',
  'settings.languageSubtitle': 'යෙදුම සඳහා භාෂාව තෝරන්න',

  // signIn
  'signIn.email': 'ඊමේල් සමඟ ඉදිරියට',
  'signIn.google': 'Google සමඟ ඉදිරියට',
  'signIn.legalAnd': ' සහ ',
  'signIn.legalPrefix': 'ඉදිරියට යාමෙන්, ඔබ අපගේ\n',
  'signIn.legalSuffix': 'වලට එකඟ වේ',
  'signIn.privacy': 'පෞද්ගලිකත්ව ප්‍රතිපත්තිය',
  'signIn.terms': 'සේවා කොන්දේසි',
  'signIn.titleHighlight': 'පිවිසීමට',
  'signIn.titlePrefix': '\nඅපි පටන් ගමු! ඔබට කැමති ආකාරය කුමක්ද ',
  'signIn.titleSuffix': '?',

  // signUp
  'signUp.and': ' සහ ',
  'signUp.emailHint': 'ඔබගේ ඊමේල් ඇතුළත් කරන්න...',
  'signUp.errEmailPass': 'කරුණාකර ඊමේල් සහ මුරපදය ඇතුළත් කරන්න.',
  'signUp.errMobile': 'කරුණාකර ඔබගේ ජංගම දුරකථන අංකය ඇතුළත් කරන්න.',
  'signUp.errName': 'කරුණාකර ඔබගේ මුල් නම සහ අවසන් නම ඇතුළත් කරන්න.',
  'signUp.firstName': 'මුල් නම',
  'signUp.firstNameHint': 'ඔබගේ මුල් නම ඇතුළත් කරන්න...',
  'signUp.haveAccount': 'දැනටමත් ගිණුමක් තිබේද? ',
  'signUp.lastName': 'අවසන් නම',
  'signUp.lastNameHint': 'ඔබගේ අවසන් නම ඇතුළත් කරන්න...',
  'signUp.legalPrefix': 'ඉදිරියට යාමෙන්, ඔබ එකඟ වන්නේ\n',
  'signUp.logIn': 'පිවිසෙන්න',
  'signUp.mobile': 'ජංගම දුරකථන අංකය',
  'signUp.mobileHint': 'ඔබගේ ජංගම දුරකථන අංකය ඇතුළත් කරන්න...',
  'signUp.privacyPolicy': 'පෞද්ගලිකත්ව ප්‍රතිපත්තිය',
  'signUp.submit': 'ලියාපදිංචි වන්න',
  'signUp.termsOfUse': 'භාවිත කොන්දේසි',

  // terms
  'terms.s1': '1. කොන්දේසි පිළිගැනීම',
  'terms.s10': '10. AI චැට්බොට්',
  'terms.s11': '11. මනෝභාව දිනපොත සහ හැඟීම් විශ්ලේෂණය',
  'terms.s12': '12. වෛද්‍ය උපදේශන',
  'terms.s13': '13. වීඩියෝ නිර්දේශ',
  'terms.s14': '14. පිළිගත හැකි භාවිතය',
  'terms.s15': '15. බුද්ධිමය දේපළ',
  'terms.s16': '16. ගිණුම අවසන් කිරීම',
  'terms.s17': '17. වගකීම් සීමා කිරීම',
  'terms.s18': '18. මෙම කොන්දේසිවල වෙනස්කම්',
  'terms.s19': '19. පාලක නීතිය',
  'terms.s2': '2. Ayu ගැන',
  'terms.s20': '20. සම්බන්ධ වන්න',
  'terms.s3': '3. වෛද්‍ය වගකීම් ප්‍රතික්ෂේපය',
  'terms.s4': '4. සුදුසුකම්',
  'terms.s5': '5. පරිශීලක ගිණුම් සහ ලියාපදිංචිය',
  'terms.s6': '6. ආරම්භය සහ සෞඛ්‍ය දත්ත',
  'terms.s7': '7. අප රැස් කරන දත්ත සහ ඒවා භාවිත කරන ආකාරය',
  'terms.s8': '8. පෞද්ගලිකත්වය සහ දත්ත ආරක්ෂාව',
  'terms.s9': '9. සහායක (රැකවරණකරු) ප්‍රවේශය',

  // todo
  'todo.add': 'එක් කරන්න',
  'todo.addFailed': 'කාර්යය එක් කිරීම අසාර්ථකයි. කරුණාකර නැවත උත්සාහ කරන්න.',
  'todo.addTask': 'කාර්යයක් එක් කරන්න',
  'todo.deleteFailed': '"{title}" මකා දැමිය නොහැක. කරුණාකර නැවත උත්සාහ කරන්න.',
  'todo.enterTask': 'කාර්යය ඇතුළත් කරන්න',
  'todo.errEnterTask': 'කරුණාකර කාර්යයක් ඇතුළත් කරන්න',
  'todo.errSelectTime': '       කරුණාකර වේලාවක් තෝරන්න',
  'todo.selectTime': 'වේලාව තෝරන්න',
  'todo.subtitle': 'සමතුලිතතාවයට ඔබගේ මග, දිනෙන් දින සකසා ඇත.\nහුස්මක් ගෙන වැදගත් දේට අවධානය යොමු කරන්න.',
  'todo.task': 'කාර්යය',
  'todo.time': 'වේලාව',
  'todo.todaysTasks': 'අද දින කාර්ය',
  'todo.weeklyTasks': 'සතිපතා කාර්ය',

  // tracker
  'tracker.add': 'එක් කරන්න',
  'tracker.addAnother': 'තවත් එකක් එක් කරන්න',
  'tracker.addMedication': 'ඖෂධ එක් කරන්න',
  'tracker.addTime': 'වේලාවක් එක් කරන්න',
  'tracker.addedSuccess': 'ඔබගේ ඖෂධය සාර්ථකව එක් කරන ලදී',
  'tracker.backToTracker': 'නිරීක්ෂකයට ආපසු',
  'tracker.chooseDate': 'දිනය තෝරන්න',
  'tracker.dailyAdherence': 'දෛනික අනුගතවීම',
  'tracker.dailyLog': 'දෛනික සටහන',
  'tracker.deleteFailed': '{name} මකා දැමිය නොහැක. කරුණාකර නැවත උත්සාහ කරන්න.',
  'tracker.emptyBody': 'අද සඳහා දැනට ඖෂධ නියම කර නොමැත. ඔබගේ දෛනික බෙහෙත් සහ විටමින් එක් කිරීමෙන් සෞඛ්‍යය රැක ගන්න.',
  'tracker.emptyTitle': 'අද සඳහා ඖෂධ\nනියම කර නොමැත',
  'tracker.feelingOkay': 'සුවෙන්ද, {name}?',
  'tracker.feelingOkayNoName': 'සුවෙන්ද?',
  'tracker.filterAll': 'සියල්ල {count}',
  'tracker.filterMissed': 'මඟහැරුණු {count}',
  'tracker.filterTaken': 'ගත් {count}',
  'tracker.markAsTaken': 'ගත් බව සලකුණු කරන්න',
  'tracker.missed': 'මඟහැරුණි',
  'tracker.missedBodyMany': 'ඔබ අද ඖෂධ {count}ක් මඟහැර ඇත.\nඔබගේ සුවය සඳහා අඛණ්ඩතාව\nඉතා වැදගත්.',
  'tracker.missedBodyOne': 'ඔබ අද ඖෂධ {count}ක් මඟහැර ඇත.\nඔබගේ සුවය සඳහා අඛණ්ඩතාව\nඉතා වැදගත්.',
  'tracker.missedCaps': 'මඟහැරුණි',
  'tracker.nameHint': 'ඖෂධයේ නම ඇතුළත් කරන්න',
  'tracker.nameOfMedicine': 'ඖෂධයේ නම',
  'tracker.onTrack': 'ඔබගේ දිනචරියාව\nහරි මගේ.',
  'tracker.repeatUntil': 'නැවත කරන්න මෙතෙක්',
  'tracker.reviewingMissed': 'මඟහැරුණු කාර්ය\nසමාලෝචනය',
  'tracker.scheduledFor': 'නියමිත වේලාව',
  'tracker.setReminders': 'මතක් කිරීම් සකසන්න',
  'tracker.showingTakenMany': 'අද ගත් ඖෂධ {count}ක් පෙන්වයි',
  'tracker.showingTakenOne': 'අද ගත් ඖෂධ {count}ක් පෙන්වයි',
  'tracker.take': 'ගන්න',
  'tracker.taken': 'ගත්තා',
  'tracker.takenCaps': 'ගත්තා',
  'tracker.times': 'වේලාවන්',
  'tracker.title': 'ඔබගේ නිරීක්ෂකය',
  'tracker.todayLabel': 'අද, {month} {day}',
  'tracker.todaysSchedule': 'අද දින කාලසටහන',
  'tracker.type': 'වර්ගය',
  'tracker.typeCapsule': 'කැප්සියුල',
  'tracker.typeInjection': 'එන්නත',
  'tracker.viewingDate': 'ඔබ බලන්නේ {day}/{month}/{year}',

  // video
  'video.errInvalid': 'වලංගු නොවන වීඩියෝ සබැඳියකි.',
  'video.errLoad': 'නිර්දේශ පූරණය කළ නොහැකි විය.',
  'video.errOpen': 'YouTube විවෘත කළ නොහැකි විය.',
  'video.errRecord': 'මෙම නැරඹීම වාර්තා කළ නොහැකි විය.',
  'video.none': 'තවම වීඩියෝ නැත.',
  'video.pullRefresh': 'නැවුම් කිරීමට පහළට අදින්න.',
  'video.pullRetry': 'නැවත උත්සාහ කිරීමට පහළට අදින්න.',
  'video.title': 'දෛනික නිර්දේශ',
  'video.views': 'නැරඹුම් {count}',
  'video.viewsB': 'නැරඹුම් {count}B',
  'video.viewsK': 'නැරඹුම් {count}K',
  'video.viewsM': 'නැරඹුම් {count}M',

  // weekday
  'weekday.short.1': 'සඳු',
  'weekday.short.2': 'අඟ',
  'weekday.short.3': 'බදා',
  'weekday.short.4': 'බ්‍රහ',
  'weekday.short.5': 'සිකු',
  'weekday.short.6': 'සෙන',
  'weekday.short.7': 'ඉරි',

  // welcome
  'welcome.haveAccount': 'දැනටමත් ගිණුමක් තිබේද? ',
  'welcome.signIn': 'පිවිසෙන්න',
  'welcome.subtitle': 'ඔබ මෙහි පැමිණීම ගැන සතුටුයි! සෑම පියවරකදීම ඔබට උදව් කිරීමට Ayu සූදානම්',
  'welcome.titleBrand': 'Ayu!',
  'welcome.titlePrefix': 'සාදරයෙන් පිළිගනිමු ',
};
