const Map<String, String> enStrings = <String, String>{

  // appt
  'appt.details': 'Appointment Details',
  'appt.documentation': 'Documentation',
  'appt.errInvalidLink': 'Invalid meeting link.',
  'appt.errNoZoomLink': 'Zoom meeting link is not available.',
  'appt.errOpenZoom': 'Unable to open Zoom meeting.',
  'appt.join': 'Join Appointment',
  'appt.meetingId': 'MEETING ID',
  'appt.noDocs': 'No documents uploaded by the doctor yet.',
  'appt.passcode': 'PASSCODE',
  'appt.platform': 'PLATFORM',
  'appt.prescription': 'Prescription',
  'appt.uploadedBy': 'Uploaded by {name} • {date}',
  'appt.uploadedDocs': 'Uploaded Documents',
  'appt.zoomDetails': 'Zoom Meeting Details {doctor}',

  // article
  'article.all': 'All',
  'article.allArticles': 'All Articles',
  'article.articleCaps': 'ARTICLE',
  'article.articles': 'Articles',
  'article.by': 'By {author}',
  'article.errLoad': 'Failed to load articles.',
  'article.introduction': 'Introduction',
  'article.none': 'No articles found.',
  'article.ourArticles': 'Our Articles',
  'article.searchHint': 'Search our 1242 articles',
  'article.suggestedTopics': 'Suggested Topics',
  'article.topicEdu': 'Edu',
  'article.topicHealth': 'Health',
  'article.topicStatus': 'Status',
  'article.topicStress': 'Stress',
  'article.unknownAuthor': 'Unknown',

  // auth
  'auth.errPhoneFormat': 'Phone must be a valid Sri Lankan mobile number (e.g. 0775455266).',
  'auth.yourPhone': 'your phone',

  // chat
  'chat.aiHelpers': 'AI Helpers',
  'chat.askAnything': 'Ask me anything...',
  'chat.chat': 'Chat',
  'chat.errHistory': 'Could not load conversation history.',
  'chat.errOlder': 'Could not load older messages.',
  'chat.errResponse': 'Sorry, I could not get a response. Please try again.',
  'chat.history': 'History',

  // chatHist
  'chatHist.deleteAll': 'Delete all the Conversation?',
  'chatHist.errDeleteAll': 'Could not delete conversations.',
  'chatHist.errDeleteOne': 'Could not delete conversation.',
  'chatHist.errLoad': 'Could not load history. Is the backend running?',
  'chatHist.noMatch': 'We\'re sorry, no message\nmatches your search',
  'chatHist.notFound': 'Not Found',
  'chatHist.searchHint': 'Search...',

  // checkout
  'checkout.bookingFee': 'Booking Fee',
  'checkout.continueToPayment': 'Continue to Payment',
  'checkout.date': 'Date',
  'checkout.doctor': 'Doctor',
  'checkout.doctorFee': 'Doctor Fee',
  'checkout.paymentDetails': 'Payment Details',
  'checkout.speciality': 'Speciality',
  'checkout.subtitle': 'Please check the details before proceeding to the payment',
  'checkout.time': 'Time',
  'checkout.title': 'Check Out',
  'checkout.totalFee': 'Total Fee',

  // common
  'common.back': 'Back',
  'common.cancel': 'Cancel',
  'common.close': 'Close',
  'common.confirm': 'Confirm',
  'common.continue': 'Continue',
  'common.delete': 'Delete',
  'common.done': 'Done',
  'common.edit': 'Edit',
  'common.error': 'Something went wrong',
  'common.loading': 'Loading...',
  'common.next': 'Next',
  'common.no': 'No',
  'common.ok': 'OK',
  'common.retry': 'Retry',
  'common.save': 'Save',
  'common.saving': 'Saving...',
  'common.search': 'Search',
  'common.seeAll': 'See All',
  'common.skip': 'Skip',
  'common.submit': 'Submit',
  'common.today': 'Today',
  'common.tomorrow': 'Tomorrow',
  'common.tryAgain': 'Please try again',
  'common.yes': 'Yes',
  'common.yesterday': 'Yesterday',

  // community
  'community.addComment': 'Add a comment...',
  'community.addPhoto': 'Add Photo',
  'community.all': 'All',
  'community.captionHint': 'Write a caption...',
  'community.createFailed': 'Failed to create post',
  'community.noPosts': 'No posts found',
  'community.photos': 'Photos',
  'community.post': 'Post',
  'community.title': 'Community',
  'community.user': 'User',
  'community.whatsHappening': 'What’s happening?',
  'community.yourPosts': 'Your Posts',

  // comp
  'comp.awaiting': 'AWAITING',
  'comp.buildCircle': 'Build your circle',
  'comp.connected': 'CONNECTED',
  'comp.emailHint': 'name@example.com',
  'comp.intro': 'Experience the journey together. Pair\nwith your partner to share insights and\nstay connected effortlessly.',
  'comp.intro1': 'Experience the journey together. Pair\n',
  'comp.intro2': 'with your partner to share insights and\n',
  'comp.intro3': 'stay connected effortlessly.',
  'comp.inviteResent': 'Invite resent successfully.',
  'comp.partnerEmail': 'PARTNER\'S EMAIL',
  'comp.privacySettings': 'Privacy Settings',
  'comp.remove': 'Remove',
  'comp.removeBody': 'This will unlink your companion. They will no longer have access to your data.',
  'comp.removeCompanion': 'Remove Companion',
  'comp.removeTitle': 'Remove Companion?',
  'comp.removed': 'Companion removed.',
  'comp.resendInvite': 'Resend Invite',
  'comp.sendDifferent': 'Send to a different email',
  'comp.sendInvite': 'Send Invite',
  'comp.title': 'Companion',
  'comp.waitingPartner': 'Waiting for your partner to join…',

  // compDash
  'compDash.card.doctor': 'Doctor\nAppointments',
  'compDash.card.mood': 'Mood\nJournal',
  'compDash.card.todo': 'To-Do\nList',
  'compDash.card.tracking': 'Tracking\nSystem',
  'compDash.everythingGeneric': 'Everything They Need',
  'compDash.everythingNamed': 'Everything {name} Needs',
  'compDash.noSharedInfo': 'The patient has not shared any information yet.',
  'compDash.plansGeneric': 'Plans For Today',
  'compDash.plansNamed': '{name}\'s Plans For Today',
  'compDash.supporting': 'Supporting {name}',

  // compSent
  'compSent.body1': 'We\'ve sent a magic link to\n',
  'compSent.body2': '. Once they\naccept, you\'ll be connected in the\nSanctuary.',
  'compSent.continue': 'Continue →',
  'compSent.pending': 'PENDING PARTNER',
  'compSent.sent': 'SENT',
  'compSent.title': 'Invitation Sent!',

  // compTodo
  'compTodo.errLoad': 'Could not load tasks.',
  'compTodo.none': 'No tasks for today.',
  'compTodo.readOnly': 'Read only · Today',
  'compTodo.restricted': 'The patient has restricted access to their to-do list.',

  // compTrack
  'compTrack.errLoad': 'Could not load medication schedule.',
  'compTrack.none': 'No medications scheduled for today.',
  'compTrack.progress': 'Today\'s Progress',
  'compTrack.restricted': 'The patient has restricted access to their tracker.',
  'compTrack.takenRatio': '{taken}/{total} taken',
  'compTrack.title': 'Medication Tracker',

  // dash
  'dash.card.chatbot': 'Chatbot',
  'dash.card.community': 'Community\nGroup Chat',
  'dash.card.companion': 'Connect\nCompanion',
  'dash.card.doctor': 'Connect With\na Doctor',
  'dash.card.donation': 'Donation\nRequest',
  'dash.card.moodJournal': 'Mood\nJournal',
  'dash.card.todo': 'To-Do List',
  'dash.card.tracking': 'Tracking\nSystem',
  'dash.card.video': 'Video\nRecommend',
  'dash.everythingYouNeed': 'Everything You Need',
  'dash.greetingAnon': 'Hi there!',
  'dash.greetingNamed': 'Hi there, {name}!',
  'dash.mindfulResources': 'Mindful Resources',
  'dash.noPlans': 'No plans for today.',
  'dash.plansForToday': 'Your Plans For Today',
  'dash.quoteOfDay': 'Quote of the day',

  // doc
  'doc.appointment': 'Doctor Appointment',
  'doc.biography': 'Biography',
  'doc.bookAppointment': 'Book Appointment',
  'doc.calendar': 'Calendar',
  'doc.catCounsellor': 'Counsellor',
  'doc.catOncologist': 'Oncologist',
  'doc.catPsychologist': 'Psychologist',
  'doc.categories': 'Categories',
  'doc.detail': 'Detail Doctor',
  'doc.errSelectDateTime': 'Please select a date and time.',
  'doc.getMoreInfo': 'Get more information',
  'doc.mySessions': 'My Sessions',
  'doc.noDoctors': 'No doctors found',
  'doc.searchHint': 'Search a Doctor...',
  'doc.specialty': 'Specialty: {specialty}',
  'doc.specialtyNA': 'Specialty not available',
  'doc.time': 'Time',

  // donation
  'donation.approvedBody': 'Your credentials and documentation\nhave been verified by our compliance team.',
  'donation.chooseFile': 'Choose File',
  'donation.docApproved': 'Document Approved',
  'donation.docRejected': 'Document Rejected',
  'donation.docStatus': 'Document Status',
  'donation.docTitle': 'Document Title',
  'donation.errActiveApp': 'You already have an active donation application.',
  'donation.errChooseFile': 'Please choose a file first.',
  'donation.errSubmit': 'Submission failed. Please try again.',
  'donation.inReview': 'In Review',
  'donation.makeARequest': 'Make a Request',
  'donation.makeRequest': 'Make a request',
  'donation.medicalDoc': 'Medical Document',
  'donation.noFile': 'No file chosen',
  'donation.rejectedBody': 'We couldn\'t verify your identity with the documents provided.',
  'donation.requestTitle': 'Donation Request',
  'donation.resubmit': 'Resubmit',
  'donation.reviewBody': 'Your document is currently being reviewed by our admins.\nResults will be provided soon.',
  'donation.statusApproved': 'APPROVED',
  'donation.statusRejected': 'REJECTED',
  'donation.statusWaiting': 'WAITING',
  'donation.submitDoc': 'Submit Document',
  'donation.tapToUpload': 'Tap to upload',
  'donation.uploadDoc': 'Upload Document',

  // editProfile
  'editProfile.backToDash': 'Back to Dashboard',
  'editProfile.passwordHint': 'Leave blank to keep current',
  'editProfile.phoneHint': '07XXXXXXXX',
  'editProfile.saveChanges': 'Save Changes',
  'editProfile.saved': 'Your changes saved successfully',
  'editProfile.title': 'Edit Profile',

  // emailVerify
  'emailVerify.afterHint': 'After you verify, press Continue to set up OTP.',
  'emailVerify.continue': 'Continue',
  'emailVerify.notYet': 'Email is not verified yet. Please check your inbox.',
  'emailVerify.resend': 'Resend email',
  'emailVerify.resent': 'Verification email sent again.',
  'emailVerify.sentTo': 'We sent a verification link to:',
  'emailVerify.title': 'Verify your email',

  // forgot
  'forgot.body': 'Enter your registered email below\nto receive password reset instruction',
  'forgot.body1': 'Enter your registered email below\n',
  'forgot.body2': 'to receive password reset instruction',
  'forgot.emailHint': 'Enter your email...',
  'forgot.errSend': 'Unable to send reset link. Please try again.',
  'forgot.heading': 'Forgot your password?',
  'forgot.login': 'Login',
  'forgot.remember': 'Remember password? ',
  'forgot.send': 'Send',
  'forgot.title': 'Forgot Password',

  // forgotSuccess
  'forgotSuccess.body': 'Please check your inbox for further instructions.',
  'forgotSuccess.noLink': 'Didn\'t receive link? ',
  'forgotSuccess.resend': 'Resend',
  'forgotSuccess.sent': 'Email has been sent!',
  'forgotSuccess.signIn': 'Sign In',

  // journal
  'journal.addPhoto': 'Add Photo',
  'journal.create': 'Create Journal',
  'journal.entryHint': 'I had a bad day today, at\nschool... It’s fine I guess...',
  'journal.errFields': 'Please fill in both title and entry',
  'journal.newEntry': 'New Journal Entry',
  'journal.selectEmotion': 'Select Your Emotion',
  'journal.titleHint': 'Feeling Bad Again',
  'journal.titleLabel': 'Journal Title',
  'journal.writeEntry': 'Write Your Entry',

  // legal
  'legal.englishNotice': 'This document is available in English only. The English version is the legally binding one.',
  'legal.privacyTitle': 'Privacy Policy',
  'legal.termsTitle': 'Terms of Service',

  // login
  'login.emailLabel': 'Email Address',
  'login.errBothFields': 'Please enter both email and password.',
  'login.errInvalidEmail': 'Please enter a valid email address.',
  'login.errOtpStart': 'Unable to start OTP verification.',
  'login.errWrongPassword': 'Incorrect password. Please try again.',
  'login.forgotPassword': 'Forgot Password',
  'login.noAccount': 'Don\'t have an account? ',
  'login.passwordHint': 'Enter your password...',
  'login.passwordLabel': 'Password',
  'login.signIn': 'Sign In',
  'login.signUp': 'Sign Up',

  // month
  'month.full.1': 'January',
  'month.full.10': 'October',
  'month.full.11': 'November',
  'month.full.12': 'December',
  'month.full.2': 'February',
  'month.full.3': 'March',
  'month.full.4': 'April',
  'month.full.5': 'May',
  'month.full.6': 'June',
  'month.full.7': 'July',
  'month.full.8': 'August',
  'month.full.9': 'September',
  'month.short.1': 'Jan',
  'month.short.10': 'Oct',
  'month.short.11': 'Nov',
  'month.short.12': 'Dec',
  'month.short.2': 'Feb',
  'month.short.3': 'Mar',
  'month.short.4': 'Apr',
  'month.short.5': 'May',
  'month.short.6': 'Jun',
  'month.short.7': 'Jul',
  'month.short.8': 'Aug',
  'month.short.9': 'Sep',

  // mood
  'mood.good': 'GOOD',
  'mood.goodDesc': 'I feel happy.',
  'mood.great': 'GREAT',
  'mood.greatDesc': 'I feel amazing.',
  'mood.low': 'LOW',
  'mood.lowDesc': 'I feel sad.',
  'mood.normal': 'NORMAL',
  'mood.normalDesc': 'I Feel Neutral.',
  'mood.veryLow': 'VERY LOW',
  'mood.veryLowDesc': 'I feel very low.',

  // moodSel
  'moodSel.checkIn': 'Let’s Check In',
  'moodSel.heading': 'How would you\ndescribe your mood?',
  'moodSel.title': 'Mood Journal',

  // moodStatus
  'moodStatus.keepJournaling': 'Keep journaling to build a mood pattern.',
  'moodStatus.moodLabel': 'Mood: {mood}',
  'moodStatus.needSupport': 'This person may need your support today.',
  'moodStatus.noHistory': 'No history yet. Add your first journal entry.',
  'moodStatus.recentJournals': 'Recent Journals',
  'moodStatus.viewAll': 'View All',

  // notif
  'notif.earlierToday': 'Earlier This Day',
  'notif.lastWeek': 'Last Week',
  'notif.markAllRead': 'Mark all read',
  'notif.medTitle': 'Time to take {name}',
  'notif.moodBody': 'Log your mood',
  'notif.moodTitle': 'How are you feeling today?',
  'notif.none': 'No notifications yet',
  'notif.taskBody': 'Due at {time}',
  'notif.taskTitle': '{title} is due soon',
  'notif.thisMonth': 'This Month',
  'notif.title': 'Notifications',

  // otp
  'otp.body': 'An OTP has been sent to your number',
  'otp.continue': 'Continue  →',
  'otp.heading': 'Enter 6 digit OTP Code',
  'otp.noCode': 'Didn\'t receive the OTP? ',
  'otp.resend': 'Re-send.',
  'otp.title': 'OTP Setup',

  // past
  'past.activeDays': 'Active journal days this year.',
  'past.allJournals': 'All Journals',
  'past.details': 'Journal Details',
  'past.entry': 'Entry',
  'past.loadMoreFailed': 'Could not load more entries.',
  'past.mood': 'Mood',
  'past.moodCaps': 'MOOD: {mood}',
  'past.newest': 'Newest',
  'past.noEntries': 'No journal entries yet.',
  'past.oldest': 'Oldest',
  'past.patientEntries': 'Patient\'s Entries',
  'past.swipeForMore': 'Swipe for more',
  'past.tapToRead': 'Tap to read full journal',
  'past.tapToReadDated': '{day}/{month} • Tap to read full journal',
  'past.title': 'Title',
  'past.yourEntries': 'Your Entries',

  // payment
  'payment.cardNumber': 'Card number',
  'payment.cardholder': 'Cardholder name',
  'payment.cvv': 'CVV',
  'payment.expDate': 'Exp. Date',
  'payment.pay': 'Pay',
  'payment.selectMethod': 'Select Payment Method',

  // privacy
  'privacy.doctorAppts': 'Doctor Appointments',
  'privacy.doctorDesc': 'Let your companion see\nupcoming doctor appointments',
  'privacy.moodDesc': 'Allow companion to see your\nmood entries',
  'privacy.moodJournal': 'Mood Journal',
  'privacy.saved': 'Privacy settings saved.',
  'privacy.subtitle': 'Control how much of your journey you share\nCompanion.',
  'privacy.title': 'Your Space, Your\nTerms',
  'privacy.todo': 'To-Do List',
  'privacy.todoDesc': 'Share your daily tasks and\npriorities',
  'privacy.tracking': 'Tracking',
  'privacy.trackingDesc': 'Enable health and activity\nmetric sharing',

  // privacyDoc
  'privacyDoc.s1': '1. What We Collect',
  'privacyDoc.s10': '10. Changes to This Policy',
  'privacyDoc.s11': '11. Contact Us',
  'privacyDoc.s2': '2. How We Use Your Information',
  'privacyDoc.s3': '3. How We Use Your Data to Improve Ayu',
  'privacyDoc.s4': '4. Who Can See Your Information',
  'privacyDoc.s5': '5. Crisis Detection',
  'privacyDoc.s6': '6. Your Data Is Kept Secure',
  'privacyDoc.s7': '7. How Long We Keep Your Data',
  'privacyDoc.s8': '8. Your Rights',
  'privacyDoc.s9': '9. Children',

  // quiz
  'quiz.back': 'Back',
  'quiz.cancerType': 'Type of cancer',
  'quiz.cancerTypeHint': 'e.g., Leukemia, Lymphoma, etc.',
  'quiz.dobCelebrate': 'We\'ll celebrate with you!',
  'quiz.dobSubtitle': 'We\'d love to celebrate\nyour birthday!',
  'quiz.dobTitle': 'When were you born?',
  'quiz.dobYearHint': 'YYYY',
  'quiz.errPickStory': 'Please select at least one story type you enjoy.',
  'quiz.errSave': 'Could not save profile: {error}',
  'quiz.finish': 'Finish',
  'quiz.genderFemale': 'Female',
  'quiz.genderMale': 'Male',
  'quiz.genderSubtitle': 'Tell us a bit about you',
  'quiz.genderTitle': 'How do you describe yourself?',
  'quiz.genderTrans': 'Transgender',
  'quiz.healthSubtitle': 'Tell us about your health (all optional)',
  'quiz.healthTitle': 'Your health journey',
  'quiz.interestCalm': 'Calm & peaceful',
  'quiz.interestDoc': 'Documentary',
  'quiz.interestEdu': 'Educational',
  'quiz.interestMusic': 'Songs & music',
  'quiz.interestScience': 'Science',
  'quiz.interestSubtitle': 'Pick what sounds fun to you!\n(You can choose more than one)',
  'quiz.interestTitle': 'What kind of stories do you like?',
  'quiz.introLine1': 'Curious about you... mind\n',
  'quiz.introLine2': ' a few things?',
  'quiz.moodCalm': 'Calm & okay',
  'quiz.moodHappy': 'Happy & excited',
  'quiz.moodSad': 'A little sad',
  'quiz.moodSubtitle': 'There\'s no wrong answer.\nJust tell us honestly',
  'quiz.moodTitle': 'How are you feeling right now?',
  'quiz.moodWorried': 'Worried or scared',
  'quiz.next': 'Next',
  'quiz.preferNotSay': 'Prefer not to say',
  'quiz.progress': '{current} of {total}',
  'quiz.relBuddhist': 'Buddhist',
  'quiz.relChristian': 'Christian',
  'quiz.relHindu': 'Hindu',
  'quiz.relMuslim': 'Muslim',
  'quiz.relOther': 'Other',
  'quiz.religionSubtitle': 'Totally optional.\nThis helps us customize your journey',
  'quiz.religionTitle': 'Do you have a faith or belief?',
  'quiz.stageAdvanced': 'Advanced',
  'quiz.stageEarly': 'Early',
  'quiz.stageNotSure': 'Not sure',
  'quiz.stageRemission': 'In remission',
  'quiz.stageTitle': 'What stage are you in?',
  'quiz.step1': 'STEP 1',
  'quiz.title': 'Quiz Time',
  'quiz.treatChemo': 'Chemotherapy',
  'quiz.treatNone': 'None right now',
  'quiz.treatRadiation': 'Radiation',
  'quiz.treatSurgery': 'Surgery',
  'quiz.treatmentTitle': 'Current treatment',

  // quote
  'quote.buddhist.0': 'The mind is everything. What you think, you become.',
  'quote.buddhist.1': 'Let go of what has passed.',
  'quote.buddhist.2': 'Every morning we are born again.',
  'quote.buddhist.3': 'Peace begins with a single breath.',
  'quote.buddhist.4': 'Compassion is the root of all healing.',
  'quote.buddhist.5': 'You yourself must strive.',
  'quote.buddhist.6': 'Small deeds done are better than great ones planned.',
  'quote.christian.0': 'With God, all things are possible.',
  'quote.christian.1': 'Be still and know that I am God.',
  'quote.christian.2': 'Fear not, for I am with you.',
  'quote.christian.3': 'Joy comes in the morning.',
  'quote.christian.4': 'I can do all things through Christ.',
  'quote.christian.5': 'Cast your worries on Him; He cares.',
  'quote.christian.6': 'The Lord is my shepherd.',
  'quote.companion.0': 'You are not alone in this.',
  'quote.companion.1': 'Small acts of care make a big difference.',
  'quote.companion.2': 'Your support means more than words can say.',
  'quote.companion.3': 'Being there is the greatest gift.',
  'quote.companion.4': 'Compassion is the root of all healing.',
  'quote.companion.5': 'Together, every step is lighter.',
  'quote.companion.6': 'Your kindness is a source of strength.',
  'quote.hindu.0': 'Do your duty and leave the rest to God.',
  'quote.hindu.1': 'Act without attachment to the outcome.',
  'quote.hindu.2': 'Where there is righteousness, there is victory.',
  'quote.hindu.3': 'The self is never truly lost.',
  'quote.hindu.4': 'Courage is your greatest virtue.',
  'quote.hindu.5': 'Let your actions reflect your values.',
  'quote.hindu.6': 'You are what your deep desire is.',
  'quote.muslim.0': 'With hardship comes ease.',
  'quote.muslim.1': 'Allah does not burden beyond capacity.',
  'quote.muslim.2': 'In His remembrance, hearts find rest.',
  'quote.muslim.3': 'Be patient. Allah is with the patient.',
  'quote.muslim.4': 'Speak good, or remain silent.',
  'quote.muslim.5': 'Trust in Allah and take action.',
  'quote.muslim.6': 'Every difficulty holds a hidden mercy.',
  'quote.other.0': 'You are stronger than you think.',
  'quote.other.1': 'Healing takes time, and that\'s okay.',
  'quote.other.2': 'One day at a time.',
  'quote.other.3': 'Small steps still move you forward.',
  'quote.other.4': 'You are not alone in this.',
  'quote.other.5': 'Breathe. You\'ve got this.',
  'quote.other.6': 'This too shall pass.',

  // sessions
  'sessions.done': 'Done',
  'sessions.late': 'Late',
  'sessions.myAppts': 'My Appointments',
  'sessions.none': 'No appointments yet',
  'sessions.past': 'Past',
  'sessions.patientAppts': 'Patient\'s Appointments',
  'sessions.upcoming': 'Upcoming',

  // settings
  'settings.language': 'Language',
  'settings.languageChanged': 'Language updated',
  'settings.languageSubtitle': 'Choose the language for the app',

  // signIn
  'signIn.email': 'Continue with Email',
  'signIn.google': 'Continue with Google',
  'signIn.legalAnd': ' and ',
  'signIn.legalPrefix': 'By continuing, you agree to\nour ',
  'signIn.legalSuffix': '',
  'signIn.privacy': 'Privacy Policy',
  'signIn.terms': 'Terms of Service',
  'signIn.titleHighlight': 'sign in',
  'signIn.titlePrefix': '\nLet\'s get you started! How would you like to ',
  'signIn.titleSuffix': '?',

  // signUp
  'signUp.and': ' and ',
  'signUp.emailHint': 'Enter your email...',
  'signUp.errEmailPass': 'Please enter email and password.',
  'signUp.errMobile': 'Please enter your mobile number.',
  'signUp.errName': 'Please enter your first and last name.',
  'signUp.firstName': 'First Name',
  'signUp.firstNameHint': 'Enter your First Name...',
  'signUp.haveAccount': 'Already have an account? ',
  'signUp.lastName': 'Last Name',
  'signUp.lastNameHint': 'Enter your Last Name...',
  'signUp.legalPrefix': 'By continuing, you agree to\n',
  'signUp.logIn': 'Log In',
  'signUp.mobile': 'Mobile Number',
  'signUp.mobileHint': 'Enter your Mobile Number...',
  'signUp.privacyPolicy': 'Privacy Policy',
  'signUp.submit': 'Sign Up',
  'signUp.termsOfUse': 'Terms of Use',

  // terms
  'terms.s1': '1. Acceptance of Terms',
  'terms.s10': '10. AI Chatbot',
  'terms.s11': '11. Mood Journal & Sentiment Analysis',
  'terms.s12': '12. Doctor Consultations',
  'terms.s13': '13. Video Recommendations',
  'terms.s14': '14. Acceptable Use',
  'terms.s15': '15. Intellectual Property',
  'terms.s16': '16. Account Termination',
  'terms.s17': '17. Limitation of Liability',
  'terms.s18': '18. Changes to These Terms',
  'terms.s19': '19. Governing Law',
  'terms.s2': '2. About Ayu',
  'terms.s20': '20. Contact',
  'terms.s3': '3. Medical Disclaimer',
  'terms.s4': '4. Eligibility',
  'terms.s5': '5. User Accounts & Registration',
  'terms.s6': '6. Onboarding & Health Data',
  'terms.s7': '7. Data We Collect and How We Use It',
  'terms.s8': '8. Privacy & Data Security',
  'terms.s9': '9. Companion (Caregiver) Access',

  // todo
  'todo.add': 'Add',
  'todo.addFailed': 'Failed to add task. Please try again.',
  'todo.addTask': 'Add Task',
  'todo.deleteFailed': 'Unable to delete "{title}". Please try again.',
  'todo.enterTask': 'Enter task',
  'todo.errEnterTask': 'Please enter a task',
  'todo.errSelectTime': '       Please select a time',
  'todo.selectTime': 'Select Time',
  'todo.subtitle': 'Your path to balance, outlined day by day.\nTake a breath and focus on what matters.',
  'todo.task': 'Task',
  'todo.time': 'Time',
  'todo.todaysTasks': 'Today\'s Tasks',
  'todo.weeklyTasks': 'Weekly Tasks',

  // tracker
  'tracker.add': 'Add',
  'tracker.addAnother': 'Add another',
  'tracker.addMedication': 'Add Medication',
  'tracker.addTime': 'Add Time',
  'tracker.addedSuccess': 'Your medication successfully added',
  'tracker.backToTracker': 'Back to tracker',
  'tracker.chooseDate': 'Choose date',
  'tracker.dailyAdherence': 'DAILY ADHERENCE',
  'tracker.dailyLog': 'DAILY LOG',
  'tracker.deleteFailed': 'Unable to delete {name}. Please try again.',
  'tracker.emptyBody': 'There are currently no medications scheduled for today. Stay on top of your health by adding your daily prescriptions and vitamins.',
  'tracker.emptyTitle': 'No Medications are\nScheduled for Today',
  'tracker.feelingOkay': 'Feeling okay, {name}?',
  'tracker.feelingOkayNoName': 'Feeling okay?',
  'tracker.filterAll': 'All {count}',
  'tracker.filterMissed': 'Missed {count}',
  'tracker.filterTaken': 'Taken {count}',
  'tracker.markAsTaken': 'Mark as Taken',
  'tracker.missed': 'Missed',
  'tracker.missedBodyMany': 'You\'ve missed {count} medications today.\nConsistency is key for your recovery\njourney.',
  'tracker.missedBodyOne': 'You\'ve missed {count} medication today.\nConsistency is key for your recovery\njourney.',
  'tracker.missedCaps': 'MISSED',
  'tracker.nameHint': 'Enter medicine name',
  'tracker.nameOfMedicine': 'Name of medicine',
  'tracker.onTrack': 'Your routine is\non track.',
  'tracker.repeatUntil': 'Repeat until',
  'tracker.reviewingMissed': 'Reviewing\nMissed Tasks',
  'tracker.scheduledFor': 'SCHEDULED FOR',
  'tracker.setReminders': 'Set Reminders',
  'tracker.showingTakenMany': 'Showing {count} medications taken today',
  'tracker.showingTakenOne': 'Showing {count} medication taken today',
  'tracker.take': 'Take',
  'tracker.taken': 'Taken',
  'tracker.takenCaps': 'TAKEN',
  'tracker.times': 'Times',
  'tracker.title': 'Your Tracker',
  'tracker.todayLabel': 'Today, {month} {day}',
  'tracker.todaysSchedule': 'TODAY\'S SCHEDULE',
  'tracker.type': 'Type',
  'tracker.typeCapsule': 'Capsule',
  'tracker.typeInjection': 'Injection',
  'tracker.viewingDate': 'You are viewing {day}/{month}/{year}',

  // video
  'video.errInvalid': 'Invalid video link.',
  'video.errLoad': 'Could not load recommendations.',
  'video.errOpen': 'Could not open YouTube.',
  'video.errRecord': 'Could not record this view.',
  'video.none': 'No videos yet.',
  'video.pullRefresh': 'Pull down to refresh.',
  'video.pullRetry': 'Pull down to retry.',
  'video.title': 'Daily Recommendations',
  'video.views': '{count} views',
  'video.viewsB': '{count}B views',
  'video.viewsK': '{count}K views',
  'video.viewsM': '{count}M views',

  // weekday
  'weekday.short.1': 'MON',
  'weekday.short.2': 'TUE',
  'weekday.short.3': 'WED',
  'weekday.short.4': 'THU',
  'weekday.short.5': 'FRI',
  'weekday.short.6': 'SAT',
  'weekday.short.7': 'SUN',

  // welcome
  'welcome.haveAccount': 'Already have an account? ',
  'welcome.signIn': 'Sign In',
  'welcome.subtitle': 'So glad you\'re here! Ayu is ready to help you every step of the way',
  'welcome.titleBrand': 'Ayu!',
  'welcome.titlePrefix': 'Welcome to ',
};
